### ISSUE TITLE
Unable to run the test code

### ISSUE THREAD

**Issue by JianrongTan** [21cmfast/21cmEMU#69]
After installing the package using pip in a new environment
`pip install py21cmemu `
 I ran 
`from py21cmemu import Emulator; emu_instance = Emulator()`
and I received the error message 
`OSError: Cannot parse file b'../21cmEMU/21cmEMU/saved_model.pb': Error parsing message.`

Not sure how to solve this problem. Do I need to manually download the model somewhere? Thanks!

**Comment by DanielaBreitman** [comment]
Awesome, thanks for sharing your solution.

**Comment by DanielaBreitman** [comment]
After further investigation, this error occurs when the user does not have `git-lfs` installed on their system, which makes the emulator files install only partially. In versions above v1.0.8, an error should be thrown when this happens!
